spring:
    application:
        name: zuul

server:
    port: 8989

#zuul:
#    routes:
#        transaction-facade:
#            path: /transaction/**
#            serviceId: transaction-facade-srv
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 2
      healthCheckUrlPath: /dockerhealth
